version: '3.8'

services:
  workshop_app:
    container_name: workshop_app
    restart: always
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - /mnt/ncode_face_vol:/mnt/ncode_face_vol
  workshop_nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: workshop_nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - workshop_app